# Generated by Django 5.0.2 on 2024-04-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titile',
            new_name='title',
        ),
    ]
